name: 🪳 Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
# assignees:
#   - assign your sdk team e.g., onesignal/unity
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Provide a thorough description of whats going on.
      placeholder: The latest version of the SDK causes my screen to go blank when I tap on the screen three times.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce?
      description: Provide as much detail as posible to reproduce the issue.
      placeholder: |
        1. Install vX.Y.Z of dependency
        2. Launch the app on iOS device
        3. Tap the screen three times
        4. Note that the app crashes
      render: Markdown
    validations:
      required: true
  - type: textarea
    id: what-are-expectations
    attributes:
      label: What did you expect to happen?
      description: Also tell us, what did you expect to happen?
      placeholder: I expected the app to continue running no matter how many times I tap the screen.
    validations:
      required: true
  - type: textarea
    id: expo-sdk-version
    attributes:
      label: OneSignal Expo SDK version
      description: The version of the OneSignal Expo SDK used in your app.
      placeholder: 1.0.0
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you having an issue with?
      multiple: true
      options:
        - iOS
        - Android
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](#insert-project-code-of-conduct-here)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
